version: '3'

services:
    basement_bot_ui:
        image: ${BASEMENT_BOT_UI_IMAGE_TAG:-effprime/basement-bot-ui:prod}
        container_name: ${BASEMENT_BOT_UI_CONTAINER_NAME:-basement_bot_ui}
        environment:
            - DEBUG=0
        env_file: .env
        restart: always
        ports:
            - ${UI_PORT:-80}:80